### ISSUE TITLE
2021 roadmap

### ISSUE THREAD

**Issue by emmyft** [osc-delft/ideas-and-plans#5]
Contributors: [TU Delft data stewards](https://www.tudelft.nl/en/library/research-data-management/r/support/data-stewardship/contact/), Paula Martinez Lavanchy

This roadmap is open for comments, revisions, alternative suggestions - please comment in this issue, box below 👇 

## What is Open Science Community Delft, and what is our vision?

We are TU Delft researchers, staff, teachers and students interested in open science. 

Our vision is to connect and work with researchers, staff, teachers and students at TU Delft to recognise, share and learn open science practices so that we can together create an open, inclusive culture of learning at TU Delft. 

## How can you get involved?
- [Sign up](https://osc-delft.github.io) to become an OSCD member
- [Check the issue list](https://github.com/osc-delft/osc-delft.github.io/issues) to help us improve the community website 
- [Use the idea sandbox](https://github.com/osc-delft/ideas-and-plans) to propose new initiatives/activities that we can do as a community, or give feedback to others' ideas!
- **Give feedback on this roadmap by commenting on this issue!**

Please be mindful that we expect everyone to respect and abide by our community [Code of Conduct](https://github.com/osc-delft/osc-delft.github.io/blob/master/CODE_OF_CONDUCT.md) when contributing - please help keep our community welcoming and safe :sunflower:

## Timeline

Working backwards!

### By the **end of March 2021**, we have:

- [x] **a community website up and runnning**: people can find out about the community, our members and activities online
- [x] **a new members workflow: potential members can sign-up**, they will be onboarded smoothly, with their profiles on the website where applicable
- [x] **a way to grow**: the community have the infrastructure to engage with open science topics beyond open data
- [x] some **understanding of community members' needs and wants** when it comes to recognising, sharing and learning open science practices

### By the **end of July 2021**, we have:
- [ ] **a core team** to help organise and plan things moving forward
- [x] maybe some coffee hours where people can come and discuss event ideas? :coffee: 

### By the **end of 2021**, we have:
- [x] a forum/place to ask your software questions and share your knowledge, which will be a prototype of the wider learning and sharing platform for open science
- [ ] 2+ pieces of member (co)authored content on our stories page
- [x] an event, on a topic of open science that is not data, software or hardware
- [x] give a talk about the community to raise its profile - increase the impact of content contributions?
- [ ] (some goals from the open hardware team)
- [ ] (some goals from data champions)

### By the **end of 2022**, we have:
- [ ] a forum/place to ask your open science questions and share your knowledge (or not, depending on prototype success)
- [ ] a continuous flow of content to our community stories page, where members share their stories and thoughts on open science
- [ ] at least one other "new" intiative that has nothing to do with data, software or hardware (or not, depending on event success)
- [ ] more goals from open hardware and data champions
